name: Deployment

on:
   issue_comment:
     types: [created]    
jobs:
  Deployment_test:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deployment_test'}}
    runs-on: ubuntu-22.04
    steps:
      - name: Remote Workflow
        uses: igallart/ pokedex-for-ci/.github/workflows/workflow.yml@main