name: Deploy to TEST

on:
  issue_comment:
    types: [created]  
jobs:
  deploy_test:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deploy_test'}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/head"
          fetch-depth: 1
          path: "PR"
      - run: pwd
