name: Test

on:
  push:
    branches:
      - main
jobs:
  hello_world:
    runs-on: ubuntu-22.04
    concurrency:
        group: ${{ github.ref }}
        cancel-in-progress: true
    steps:      
      - name: saluda
        run: |
          echo "HOLA"
      - name: numero de cpus
        run: $nproc
      - name: Dime la ram
        run: free -h
      - name: dime todo
        run: sleep 62