name: Deploy to TEST

on:
  issue_comment:
    types: [created]
  
   
    branches:
      - main
jobs:
  deploy_test:
    concurrency:
        group: ${{ github.ref }}
        cancel-in-progress: true
    runs-on: ubuntu-22.04
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deploy_test'}}
    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    
      - run: ls -l