name: Deploy to TEST

on:
  # issue_comment:
  #   types: [created]
  push:
    branches:
      - main
jobs:
  deploy_test:
    # if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deploy_test'}}
    # concurrency:
    #   group: ${{ github.ref }}
    #   cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: Create SSH config
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
          echo "${{ secrets.SSH_GLOBAL_KEY }}" > ~/.ssh/global_key
          chmod 600 ~/.ssh/private_key ~/.ssh/global_key
          cat >>~/.ssh/config <<END
          Host odoo_remote
            HostName ${{ vars.SSH_ODOO_HOST }}
            User ${{ vars.SSH_ODOO_USER }}
            Port ${{ vars.SSH_ODOO_PORT }}
            IdentityFile ~/.ssh/private_key
            IdentityFile ~/.ssh/global_key
            StrictHostKeyChecking no
          END
          chmod 700 ~/.ssh
          echo ~/.ssh/config
      # - name: Checkout Pull Request ${{ github.event.issue.pull_request.title }}
      - name: Checkout Pull Request
        uses: actions/checkout@v3
        with:
          # ref: "refs/pull/${{ github.event.issue.number }}/head"
          path: "addons-custom"
      - name: Copy addons-custom to ${{ vars.SSH_ODOO_HOST }}
        run: |
          echo "XX ${{ vars.ODOO_HOST }} ZZ"
          # ssh odoo_remote 'rm -rf /tmp/addons-custom'
          # rsync -aq addons-custom odoo_remote:/tmp/
          # ssh odoo_remote 'systemctl stop $ODOO_SERVICE_TEST'
          # ssh odoo_remote 'rm -rf $ODOO_HOST'
