name: Deploy to TEST

on:
  # issue_comment:
  #   types: [created]
  push:
    branches:
      - main
jobs:
  deploy_test:
    # if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deploy_test'}}
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          # ref: "refs/pull/${{ github.event.issue.number }}/head"
          fetch-depth: 1
          path: "PR"
      - run: pwd && ls -l PR
